name: Test the actio n

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: karpikpl/pylint-action@main
        with:
          python-version: '3.13'

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.result }}"